/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PullRequestsRouteImport } from './routes/pull-requests'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsUsageRouteImport } from './routes/settings.usage'
import { Route as SettingsThemeBuilderRouteImport } from './routes/settings.theme-builder'
import { Route as SettingsSkillsRouteImport } from './routes/settings.skills'
import { Route as SettingsMobileRouteImport } from './routes/settings.mobile'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsFeedbackRouteImport } from './routes/settings.feedback'
import { Route as SettingsCreditsRouteImport } from './routes/settings.credits'
import { Route as SettingsComputerUseRouteImport } from './routes/settings.computer-use'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as SettingsAccountRouteImport } from './routes/settings.account'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PullRequestsRoute = PullRequestsRouteImport.update({
  id: '/pull-requests',
  path: '/pull-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsUsageRoute = SettingsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsThemeBuilderRoute = SettingsThemeBuilderRouteImport.update({
  id: '/theme-builder',
  path: '/theme-builder',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSkillsRoute = SettingsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMobileRoute = SettingsMobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsFeedbackRoute = SettingsFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCreditsRoute = SettingsCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsComputerUseRoute = SettingsComputerUseRouteImport.update({
  id: '/computer-use',
  path: '/computer-use',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/goals': typeof GoalsRoute
  '/kanban': typeof KanbanRoute
  '/pull-requests': typeof PullRequestsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/computer-use': typeof SettingsComputerUseRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/settings/feedback': typeof SettingsFeedbackRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/mobile': typeof SettingsMobileRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/theme-builder': typeof SettingsThemeBuilderRoute
  '/settings/usage': typeof SettingsUsageRoute
}
export interface FileRoutesByTo {
  '/goals': typeof GoalsRoute
  '/kanban': typeof KanbanRoute
  '/pull-requests': typeof PullRequestsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/computer-use': typeof SettingsComputerUseRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/settings/feedback': typeof SettingsFeedbackRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/mobile': typeof SettingsMobileRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/theme-builder': typeof SettingsThemeBuilderRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/': typeof ChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/goals': typeof GoalsRoute
  '/kanban': typeof KanbanRoute
  '/pull-requests': typeof PullRequestsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/computer-use': typeof SettingsComputerUseRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/settings/feedback': typeof SettingsFeedbackRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/mobile': typeof SettingsMobileRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/theme-builder': typeof SettingsThemeBuilderRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/_chat/': typeof ChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/goals'
    | '/kanban'
    | '/pull-requests'
    | '/settings'
    | '/welcome'
    | '/$threadId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/computer-use'
    | '/settings/credits'
    | '/settings/feedback'
    | '/settings/general'
    | '/settings/mobile'
    | '/settings/skills'
    | '/settings/theme-builder'
    | '/settings/usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/goals'
    | '/kanban'
    | '/pull-requests'
    | '/settings'
    | '/welcome'
    | '/$threadId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/computer-use'
    | '/settings/credits'
    | '/settings/feedback'
    | '/settings/general'
    | '/settings/mobile'
    | '/settings/skills'
    | '/settings/theme-builder'
    | '/settings/usage'
    | '/'
  id:
    | '__root__'
    | '/_chat'
    | '/goals'
    | '/kanban'
    | '/pull-requests'
    | '/settings'
    | '/welcome'
    | '/_chat/$threadId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/computer-use'
    | '/settings/credits'
    | '/settings/feedback'
    | '/settings/general'
    | '/settings/mobile'
    | '/settings/skills'
    | '/settings/theme-builder'
    | '/settings/usage'
    | '/_chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  GoalsRoute: typeof GoalsRoute
  KanbanRoute: typeof KanbanRoute
  PullRequestsRoute: typeof PullRequestsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pull-requests': {
      id: '/pull-requests'
      path: '/pull-requests'
      fullPath: '/pull-requests'
      preLoaderRoute: typeof PullRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/usage': {
      id: '/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof SettingsUsageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/theme-builder': {
      id: '/settings/theme-builder'
      path: '/theme-builder'
      fullPath: '/settings/theme-builder'
      preLoaderRoute: typeof SettingsThemeBuilderRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/skills': {
      id: '/settings/skills'
      path: '/skills'
      fullPath: '/settings/skills'
      preLoaderRoute: typeof SettingsSkillsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/mobile': {
      id: '/settings/mobile'
      path: '/mobile'
      fullPath: '/settings/mobile'
      preLoaderRoute: typeof SettingsMobileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/feedback': {
      id: '/settings/feedback'
      path: '/feedback'
      fullPath: '/settings/feedback'
      preLoaderRoute: typeof SettingsFeedbackRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/credits': {
      id: '/settings/credits'
      path: '/credits'
      fullPath: '/settings/credits'
      preLoaderRoute: typeof SettingsCreditsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/computer-use': {
      id: '/settings/computer-use'
      path: '/computer-use'
      fullPath: '/settings/computer-use'
      preLoaderRoute: typeof SettingsComputerUseRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsComputerUseRoute: typeof SettingsComputerUseRoute
  SettingsCreditsRoute: typeof SettingsCreditsRoute
  SettingsFeedbackRoute: typeof SettingsFeedbackRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsMobileRoute: typeof SettingsMobileRoute
  SettingsSkillsRoute: typeof SettingsSkillsRoute
  SettingsThemeBuilderRoute: typeof SettingsThemeBuilderRoute
  SettingsUsageRoute: typeof SettingsUsageRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsComputerUseRoute: SettingsComputerUseRoute,
  SettingsCreditsRoute: SettingsCreditsRoute,
  SettingsFeedbackRoute: SettingsFeedbackRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsMobileRoute: SettingsMobileRoute,
  SettingsSkillsRoute: SettingsSkillsRoute,
  SettingsThemeBuilderRoute: SettingsThemeBuilderRoute,
  SettingsUsageRoute: SettingsUsageRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  GoalsRoute: GoalsRoute,
  KanbanRoute: KanbanRoute,
  PullRequestsRoute: PullRequestsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
