import {
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  KanbanItemCreatedPayload as ContractsKanbanItemCreatedPayloadSchema,
  KanbanItemUpdatedPayload as ContractsKanbanItemUpdatedPayloadSchema,
  KanbanItemMovedPayload as ContractsKanbanItemMovedPayloadSchema,
  KanbanItemAssignedPayload as ContractsKanbanItemAssignedPayloadSchema,
  KanbanItemUnassignedPayload as ContractsKanbanItemUnassignedPayloadSchema,
  KanbanItemBlockedPayload as ContractsKanbanItemBlockedPayloadSchema,
  KanbanItemUnblockedPayload as ContractsKanbanItemUnblockedPayloadSchema,
  KanbanItemCompletedPayload as ContractsKanbanItemCompletedPayloadSchema,
  KanbanItemNoteAddedPayload as ContractsKanbanItemNoteAddedPayloadSchema,
  KanbanItemDeletedPayload as ContractsKanbanItemDeletedPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadResumeStateSetPayload as ContractsThreadResumeStateSetPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
} from "contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;
export const KanbanItemCreatedPayload = ContractsKanbanItemCreatedPayloadSchema;
export const KanbanItemUpdatedPayload = ContractsKanbanItemUpdatedPayloadSchema;
export const KanbanItemMovedPayload = ContractsKanbanItemMovedPayloadSchema;
export const KanbanItemAssignedPayload = ContractsKanbanItemAssignedPayloadSchema;
export const KanbanItemUnassignedPayload = ContractsKanbanItemUnassignedPayloadSchema;
export const KanbanItemBlockedPayload = ContractsKanbanItemBlockedPayloadSchema;
export const KanbanItemUnblockedPayload = ContractsKanbanItemUnblockedPayloadSchema;
export const KanbanItemCompletedPayload = ContractsKanbanItemCompletedPayloadSchema;
export const KanbanItemNoteAddedPayload = ContractsKanbanItemNoteAddedPayloadSchema;
export const KanbanItemDeletedPayload = ContractsKanbanItemDeletedPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadResumeStateSetPayload = ContractsThreadResumeStateSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;
